# TODO: add redcarpet extensions when becomming comfortable with markdown
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:           pretty

# Setup
title:               'grcanosa'
tagline:             'Personal thought drawer'
description:         ''
url:                 grcanosa.github.io
baseurl:             '/'
# Use paginate to set the number of pages shown
paginate:            5

excerpt_separator: '<br>'

author:
  name: 'Gonzalo Rodríguez Canosa'
  github: grcanosa
  email_md5: bddd232db634cd50a4e71e669a61514e
  #google_analytics_id: UA-72555431-1
  #google_analytics_url: mlampros.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/grcanosa
  

